(()=>{
'use strict';
const E=window.PortSimEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let world=E.generate('PORT-OPS-01',{policy:'hybrid'}),paused=false,speed=1,last=performance.now(),acc=0,radioCutoff=0,lastUi=0,selectedShipId=null;
const renderer=new HarborRenderer($('#harbor'));let chart=null;
renderer.onShipSelected=id=>{selectedShipId=id;renderQueue();renderBerths();updateMapButtons()};
renderer.onCameraChanged=cam=>{if($('#mapZoom'))$('#mapZoom').textContent=`${Math.round(cam.zoom*100)}%`};
function fmtTime(min){const d=Math.floor(min/1440)+1,m=min%1440,h=Math.floor(m/60),mm=m%60;return`DAY ${String(d).padStart(2,'0')} · ${String(h).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}
function hours(min){return(min/60).toFixed(1)}function pct(v){return`${Math.round(v*100)}%`}const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function stageLabel(s){return E.STAGES[s.stage]||s.stage}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function renderAll(){renderer.render(world);renderStatus();renderKPIs();renderBerths();renderQueue();renderRadio();renderChart();updateMapButtons()}
function renderStatus(){const st=E.stats(world);$('#clock').textContent=fmtTime(world.time);$('#weatherText').textContent=world.weather.label;$('#weatherDetail').textContent=`${world.weather.wind} kn / ${world.weather.vis} nm`;$('#policyBadge').textContent=world.policy.toUpperCase();$('#shipsActive').textContent=world.ships.filter(s=>s.stage!=='COMPLETE').length;$('#policySelect').value=world.policy;$('#objectiveBadge').textContent=`OR ${Math.round(st.objective)}`}
function renderKPIs(){const s=E.stats(world);$('#kQueue').textContent=s.queue;$('#kWait').textContent=hours(s.avgWait);$('#kTurn').textContent=hours(s.avgTurn);$('#kThrough').textContent=s.throughput.toFixed(1);setUtil('Berth',s.berthUtil);setUtil('Pilot',s.pilotUtil);setUtil('Tug',s.tugUtil);setUtil('Crane',s.craneUtil);$('#lambda').textContent=s.lambda.toFixed(3);$('#littleL').textContent=s.littleL.toFixed(2);$('#objective').textContent=Math.round(s.objective)}
function setUtil(k,v){$(`#u${k}`).style.width=`${clamp(v*100,0,100)}%`;$(`#u${k}Text`).textContent=pct(v)}
function focusShip(id){selectedShipId=Number(id);renderer.focusShip(selectedShipId,true);renderQueue();renderBerths();updateMapButtons()}
function renderBerths(){$('#berthBoard').innerHTML=world.berths.map(b=>{const ship=b.shipId!=null?world.ships.find(s=>s.id===b.shipId):null;return`<article class="berth ${ship?'occupied':'free'} ${ship?.id===selectedShipId?'selected':''}" ${ship?`data-focus-ship="${ship.id}" tabindex="0" role="button"`:''}><div class="berth-top"><div><i></i><b>${esc(b.name)}</b><span>${esc(b.kind)}</span></div><em>${ship?'OCCUPIED':'AVAILABLE'}</em></div>${ship?`<h3>${esc(ship.name)}</h3><p>${esc(E.TYPES[ship.type].label)} · LOA ${ship.loa} m · ${ship.draft.toFixed(1)} m draft</p><div class="berth-progress"><span>${esc(stageLabel(ship))}</span><b>${ship.stage==='CARGO'?`${Math.round((1-ship.remainingCargo/ship.cargo)*100)}% cargo`:ship.stage==='MOORING'?'All fast sequence':'Port operation'}</b></div>`:`<p class="berth-empty">Max LOA ${b.maxLoa} m · Max draft ${b.maxDraft.toFixed(1)} m · ${b.craneCap} crane positions</p>`}</article>`}).join('');$$('[data-focus-ship]').forEach(el=>{el.onclick=()=>focusShip(el.dataset.focusShip);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focusShip(el.dataset.focusShip)}}})}
function renderQueue(){const active=world.ships.filter(s=>s.stage!=='COMPLETE').sort((a,b)=>{const qa=a.stage==='ANCHORAGE'?0:1,qb=b.stage==='ANCHORAGE'?0:1;return qa-qb||a.arrival-b.arrival});$('#queueBody').innerHTML=active.length?active.map((s,i)=>{const score=s.stage==='ANCHORAGE'?E.queueScore(world,s,world.policy):null;return`<tr data-ship-row="${s.id}" class="queue-click stage-${s.stage.toLowerCase()} ${s.id===selectedShipId?'selected-row':''}" title="Focus ${esc(s.name)} on the harbor map"><td>${String(i+1).padStart(2,'0')}</td><td><b>${esc(s.name)}</b><small>#${s.id} · click to locate</small></td><td>${esc(E.TYPES[s.type].label)}</td><td>${s.loa} m</td><td>${s.draft.toFixed(1)} m</td><td><span class="stage-chip">${esc(stageLabel(s))}</span></td><td>${hours(s.wait)} h</td><td>${s.berthId==null?'—':esc(world.berths[s.berthId].name)}</td><td>${score==null?'—':Math.round(score)}</td></tr>`}).join(''):`<tr><td colspan="9" class="empty">No active vessels.</td></tr>`;$$('[data-ship-row]').forEach(row=>row.onclick=()=>focusShip(row.dataset.shipRow))}
function renderRadio(){const rows=world.radio.filter(r=>r.id>radioCutoff).slice(0,22);$('#radioLog').innerHTML=rows.length?rows.map(r=>`<article class="${r.shipId===selectedShipId?'active-radio':''}" ${r.shipId!=null?`data-radio-ship="${r.shipId}"`:''}><time>${fmtTime(r.t).replace('DAY ','D')}</time><div><b>${esc(r.from)}</b><p>${esc(r.text)}</p></div></article>`).join(''):`<div class="empty">No radio traffic in current view.</div>`;$$('[data-radio-ship]').forEach(row=>row.onclick=()=>focusShip(row.dataset.radioShip))}
function initChart(){chart=new Chart($('#queueChart'),{type:'line',data:{labels:[],datasets:[{label:'Anchorage queue',data:[],borderColor:'#63d3ff',backgroundColor:'rgba(99,211,255,.12)',fill:true,tension:.25,pointRadius:0},{label:'Berth utilization %',data:[],borderColor:'#ffd166',backgroundColor:'transparent',tension:.2,pointRadius:0,yAxisID:'y1'}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{labels:{color:'#9fb4c0',boxWidth:12}}},scales:{x:{ticks:{color:'#738c9b',maxTicksLimit:8},grid:{color:'rgba(255,255,255,.04)'}},y:{beginAtZero:true,ticks:{color:'#738c9b'},grid:{color:'rgba(255,255,255,.04)'}},y1:{beginAtZero:true,max:100,position:'right',ticks:{color:'#9f8b56'},grid:{display:false}}}}})}
function renderChart(){if(!chart)return;const h=world.history.slice(-80);chart.data.labels=h.map(x=>fmtTime(x.t).replace('DAY ','D'));chart.data.datasets[0].data=h.map(x=>x.queue);chart.data.datasets[1].data=h.map(x=>Math.round(x.berthUtil*100));chart.update('none')}
function frame(now){const dt=Math.min(.25,(now-last)/1000);last=now;if(!paused){acc+=dt*speed;let guard=0;while(acc>=1&&guard++<180){E.step(world,1);acc-=1}}if(now-lastUi>180){renderAll();lastUi=now}requestAnimationFrame(frame)}
function openModal(){$('#scenarioModal').classList.remove('hidden');$('#seedInput').focus()}function closeModal(){$('#scenarioModal').classList.add('hidden')}
function createScenario(){world=E.generate($('#seedInput').value.trim()||'PORT-OPS-01',{policy:$('#modalPolicy').value,arrivalMean:+$('#arrivalInput').value,pilots:+$('#pilotInput').value,tugs:+$('#tugInput').value,cranes:+$('#craneInput').value});radioCutoff=0;selectedShipId=null;paused=false;acc=0;$('.pause').textContent='❚❚ Pause';closeModal();renderer.centerPort();renderAll();toast('New port scenario started.')}
function save(){localStorage.setItem('port-congestion-save',E.serialize(world));toast('Scenario saved locally.')}function load(){const s=localStorage.getItem('port-congestion-save');if(!s)return toast('No local save found.');try{world=E.deserialize(s);selectedShipId=null;renderer.centerPort();renderAll();toast('Scenario restored.')}catch{toast('Save could not be loaded.')}}
function runBenchmark(){const btn=$('#benchmarkBtn');btn.disabled=true;btn.textContent='Simulating…';setTimeout(()=>{const policies=['fcfs','spt','priority','edd','hybrid'],res=[];for(const p of policies){const w=E.generate(`${world.seed}-BENCH`,{policy:p,arrivalMean:world.arrivalMean,pilots:world.resources.pilots,tugs:world.resources.tugs,cranes:world.resources.cranes});E.step(w,2880);const s=E.stats(w);res.push({policy:p,...s})}res.sort((a,b)=>a.objective-b.objective);const best=res[0].policy;$('#benchmarkResults').innerHTML=`<div class="bench-head"><span>48h controlled comparison · same seed/resources</span><b>BEST: ${best.toUpperCase()}</b></div><div class="bench-table">${res.map((r,i)=>`<button data-bench="${r.policy}" class="${i===0?'best':''}"><span>#${i+1} ${r.policy.toUpperCase()}</span><b>Objective ${Math.round(r.objective)}</b><small>Wait ${hours(r.avgWait)}h · Turn ${hours(r.avgTurn)}h · ${r.throughput.toFixed(1)} ships/day</small></button>`).join('')}</div>`;$$('[data-bench]').forEach(b=>b.onclick=()=>{E.setPolicy(world,b.dataset.bench);renderAll();toast(`${b.dataset.bench.toUpperCase()} applied to live dispatch.`)});btn.disabled=false;btn.textContent='Run 48h Policy Benchmark'},40)}
function updateMapButtons(){const f=$('#followMapBtn');if(f){f.disabled=selectedShipId==null;f.textContent=renderer.followId!=null?'Unfollow Vessel':'Follow Vessel'}if($('#mapZoom'))$('#mapZoom').textContent=`${Math.round(renderer.camera.zoom*100)}%`}
function bind(){
 $$('.speed').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;$$('.speed').forEach(x=>x.classList.toggle('active',x===b))});$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'▶ Resume':'❚❚ Pause'};$('#policySelect').onchange=e=>{E.setPolicy(world,e.target.value);renderAll()};$('#saveBtn').onclick=save;$('#loadBtn').onclick=load;$('#resetBtn').onclick=openModal;$('#createScenario').onclick=createScenario;$$('[data-close]').forEach(b=>b.onclick=closeModal);$('#arrivalInput').oninput=e=>$('#arrivalValue').textContent=e.target.value;$('#clearRadio').onclick=()=>{radioCutoff=world.radio[0]?.id||0;renderRadio()};$('#benchmarkBtn').onclick=runBenchmark;
 $('#zoomInBtn').onclick=()=>renderer.zoomBy(1.25);$('#zoomOutBtn').onclick=()=>renderer.zoomBy(.8);$('#centerMapBtn').onclick=()=>{renderer.centerPort();updateMapButtons()};$('#followMapBtn').onclick=()=>{renderer.toggleFollow(selectedShipId);updateMapButtons()};
 window.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target===document.body){e.preventDefault();$('#pauseBtn').click()}})
}
bind();initChart();renderer.centerPort(false);renderAll();requestAnimationFrame(frame);
})();