(()=>{
'use strict';
const E=window.PortSimEngine;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const POLICY={
 fcfs:['FCFS','First Come, First Served preserves arrival order among feasible vessels. It is simple and fair, but can increase mean turnaround when a long service occupies a scarce berth.'],
 spt:['SPT','Shortest Processing Time favors vessels with the lowest estimated cargo service duration. It tends to reduce average flow time, but older jobs can wait longer.'],
 edd:['EDD','Earliest Due Date gives preference to vessels with the nearest operational deadline and reduces lateness risk.'],
 priority:['Priority','Priority scheduling combines vessel class priority with accumulated anchorage waiting time.'],
 hybrid:['Hybrid Cost','A practical heuristic balances waiting time, priority, due-date slack, service duration and berth/crane fit.']
};
const TYPE_COST={container:2800,bulk:1850,tanker:3400,general:1300};
let world,renderer,paused=false,speed=1,last=performance.now(),acc=0,radioCutoff=0;
function start(seed='PORT-OPS-01',opts={}){
 world=E.generate(seed,{policy:opts.policy||'hybrid',arrivalMean:opts.arrivalMean||105,pilots:2,tugs:3,cranes:7});
 const mode=opts.weatherMode||'variable';if(mode==='fair'){world.weather={key:'fair',...E.WEATHER.fair};world.nextWeather=999999}else if(mode==='rough'){world.weather={key:'breeze',...E.WEATHER.breeze};world.nextWeather=60}
 if(!renderer)renderer=new window.HarborRenderer($('#harborStage'));
 radioCutoff=0;refresh(true);toast(`Scenario ${seed} started.`)
}
function loop(now){const dt=Math.min(.12,(now-last)/1000);last=now;if(!paused){acc+=dt*speed*1.6;let n=Math.floor(acc);if(n>0){n=Math.min(n,96);E.step(world,n);acc-=n;refresh(false)}}renderer?.render(world);requestAnimationFrame(loop)}
function timeText(min){const total=360+Math.max(0,Math.floor(min)),day=Math.floor(total/1440),m=total%1440,h=Math.floor(m/60),mm=m%60;return`${['MON','TUE','WED','THU','FRI','SAT','SUN'][day%7]} ${String(h).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}
function hours(v){return`${(v/60).toFixed(1)} h`}
function money(n){if(n>=1e6)return`$${(n/1e6).toFixed(2)}M`;if(n>=1000)return`$${(n/1000).toFixed(1)}k`;return`$${Math.round(n)}`}
function demurrage(){return world.ships.reduce((sum,s)=>sum+Math.max(0,(s.wait||0)-120)/60*(TYPE_COST[s.type]||1500),0)}
function refresh(force){if(!world)return;renderClock();renderResources();renderKPIs();renderQueue();renderBerths();renderRadio();renderDecision();if(force||world.time%5===0)drawQueueChart()}
function renderClock(){$('#portClock').textContent=timeText(world.time);const w=world.weather;$('#weatherText').textContent=`${w.label} · Wind ${w.wind} kn · Visibility ${Number(w.vis).toFixed(1)} nm${w.key==='squall'?' · MANEUVERING RESTRICTED':''}`}
function renderResources(){const r=world.resources;$('#pilotCount').textContent=`${r.pilots-r.pilotsBusy}/${r.pilots}`;$('#tugCount').textContent=`${r.tugs-r.tugsBusy}/${r.tugs}`;$('#craneCount').textContent=`${r.cranes-r.cranesBusy}/${r.cranes}`}
function renderKPIs(){const s=E.stats(world);$('#kpiQueue').textContent=s.queue;$('#kpiWait').textContent=(s.avgWait/60).toFixed(1);$('#kpiUtil').textContent=`${Math.round(s.berthUtil*100)}%`;$('#kpiThroughput').textContent=s.throughput.toFixed(2);$('#kpiDemurrage').textContent=money(demurrage());$('#kpiLittle').textContent=s.littleL.toFixed(2);const vals=world.history.map(x=>x.queue||0);$('#queuePeak').textContent=`Peak ${Math.max(0,...vals,s.queue)}`}
function stageLabel(s){return E.STAGES[s.stage]||s.stage.replaceAll('_',' ')}
function renderQueue(){const waiting=world.ships.filter(s=>s.stage==='ANCHORAGE').sort((a,b)=>E.queueScore(world,b,world.policy)-E.queueScore(world,a,world.policy));const incoming=world.ships.filter(s=>s.stage==='ARRIVING').sort((a,b)=>a.arrival-b.arrival).slice(0,5);const rows=[...waiting,...incoming];$('#queueBody').innerHTML=rows.length?rows.map((s,i)=>{const wait=s.stage==='ANCHORAGE'?s.wait:0,cls=wait>360?'wait-high':wait>120?'wait-med':'',prio='●'.repeat(Math.max(1,s.priority));return`<tr><td>${s.stage==='ANCHORAGE'?i+1:'—'}</td><td><strong>${escapeHtml(s.name)}</strong></td><td><span class="ship-type">${escapeHtml(E.TYPES[s.type].label)}</span></td><td>${s.loa} m / ${s.draft} m</td><td>${Math.round(s.cargo).toLocaleString()}</td><td>${timeText(s.arrival)}</td><td class="${cls}">${s.stage==='ANCHORAGE'?hours(wait):'Inbound ETA'}</td><td title="Priority ${s.priority}">${prio}</td><td><span class="status-pill ${s.stage==='ANCHORAGE'?'delay':''}">${escapeHtml(stageLabel(s))}</span></td></tr>`}).join(''):`<tr><td colspan="9">No vessels waiting. The roadstead is clear.</td></tr>`;
 const p=POLICY[world.policy]||POLICY.hybrid;$('#queueRuleTag').textContent=p[0]}
function renderBerths(){$('#berthCards').innerHTML=world.berths.map(b=>{const s=b.shipId!=null?world.ships.find(x=>x.id===b.shipId):null;if(!s)return`<article class="berth-card"><span class="eyebrow">${escapeHtml(b.kind)}</span><h3>${b.name}</h3><div class="berth-meta"><span>LOA ≤ ${b.maxLoa} m</span><span>Draft ≤ ${b.maxDraft} m</span><span>${b.craneCap} crane cap</span></div><div class="berth-ship"><b>AVAILABLE</b><small>Waiting for a feasible assignment</small></div></article>`;const cargoPct=s.cargo?Math.max(0,Math.min(100,(1-s.remainingCargo/s.cargo)*100)):0;return`<article class="berth-card busy"><span class="eyebrow">${escapeHtml(b.kind)}</span><h3>${b.name}</h3><div class="berth-meta"><span>LOA ≤ ${b.maxLoa} m</span><span>Draft ≤ ${b.maxDraft} m</span><span>${b.craneCap} crane cap</span></div><div class="berth-ship"><b>${escapeHtml(s.name)}</b><small>${escapeHtml(stageLabel(s))} · ${s.cranes} crane${s.cranes===1?'':'s'}</small><div class="progress"><i style="width:${cargoPct}%"></i></div><small>${cargoPct.toFixed(0)}% cargo handled</small></div></article>`}).join('')}
function renderRadio(){const list=world.radio.filter(r=>r.id>radioCutoff).slice(0,80);$('#radioLog').innerHTML=list.length?list.map(r=>`<div class="radio-line"><time>${timeText(r.t).slice(4)}</time><b>${escapeHtml(r.from)}</b><span>${escapeHtml(r.text)}</span></div>`).join(''):`<div class="radio-line system"><time>--:--</time><b>VHF</b><span>No traffic in current view.</span></div>`}
function renderDecision(){const free=world.berths.filter(b=>b.shipId==null),q=world.ships.filter(s=>s.stage==='ANCHORAGE');let candidates=[];for(const b of free)for(const s of q)if(E.compatible(s,b))candidates.push({s,b,score:E.queueScore(world,s,world.policy)+(b.craneCap>=E.TYPES[s.type].cranes[1]?25:0)});candidates.sort((a,b)=>b.score-a.score);const p=POLICY[world.policy]||POLICY.hybrid;$('#policyExplain').innerHTML=`<b>${p[0]}</b><br>${p[1]}`;if(!candidates.length){$('#decisionPanel').innerHTML=`<div class="decision-card"><b>No assignment candidate</b><p>${q.length?'Waiting vessels are currently blocked by berth dimensions/type compatibility or all suitable berths are occupied.':'The anchorage queue is empty.'}</p></div>`;return}const best=candidates[0],feas=`LOA ${best.s.loa}/${best.b.maxLoa} m · draft ${best.s.draft}/${best.b.maxDraft} m · ${best.b.craneCap} crane capacity`;$('#decisionPanel').innerHTML=`<div class="decision-card"><b>Next candidate: ${escapeHtml(best.s.name)} → ${best.b.name}</b><p>${escapeHtml(p[0])} score ${best.score.toFixed(1)}. Feasible match: ${feas}.</p><div class="score-line"><span>Queue score</span><i style="--score:${Math.min(100,Math.max(8,best.score/12))}%"></i><b>${best.score.toFixed(0)}</b></div></div>${candidates.slice(1,4).map(c=>`<div class="decision-card"><b>Alternative · ${escapeHtml(c.s.name)} → ${c.b.name}</b><p>Score ${c.score.toFixed(1)} · ${c.s.wait} min waited · service estimate ${(c.s.serviceEstimate/60).toFixed(1)} h.</p></div>`).join('')}`}
function drawQueueChart(){const c=$('#queueChart'),ctx=c.getContext('2d'),w=c.width,h=c.height,data=world.history.slice(-120).map(x=>x.queue??0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#07151c';ctx.fillRect(0,0,w,h);if(data.length<2)return;const max=Math.max(1,...data);ctx.strokeStyle='#61dff4';ctx.lineWidth=3;ctx.beginPath();data.forEach((v,i)=>{const x=i/(data.length-1)*(w-12)+6,y=h-8-v/max*(h-18);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.strokeStyle='#23444f';ctx.lineWidth=1;for(let i=1;i<4;i++){const y=i*h/4;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}
function setPolicy(p){const map={wcost:'hybrid',hybrid:'hybrid',fcfs:'fcfs',spt:'spt',priority:'priority',edd:'edd'};E.setPolicy(world,map[p]||'hybrid');renderQueue();renderDecision()}
function cycleWeather(){const keys=['fair','breeze','fog','squall'],i=(keys.indexOf(world.weather.key)+1)%keys.length,key=keys[i];world.weather={key,...E.WEATHER[key]};world.nextWeather=world.time+150;world.events.unshift({id:++world.eventSeq,t:world.time,type:'weather',text:`Observer weather override: ${world.weather.label}.`,shipId:null});toast(`${world.weather.label} weather applied.`);refresh(true)}
function inject(){world.nextArrival=world.time+1;toast('Additional vessel entered the VTS arrival stream.')}
function openModal(){$('#scenarioModal').classList.remove('hidden')}function closeModal(){$('#scenarioModal').classList.add('hidden')}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bind(){$$('.speed').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;$$('.speed').forEach(x=>x.classList.toggle('active',x===b))});$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'Resume':'Pause'};$('#policySelect').onchange=e=>setPolicy(e.target.value);$('#resetBtn').onclick=openModal;$('#addShipBtn').onclick=inject;$('#weatherBtn').onclick=cycleWeather;$('#clearRadioBtn').onclick=()=>{radioCutoff=world.radio[0]?.id||0;renderRadio()};$$('[data-close]').forEach(b=>b.onclick=closeModal);$('#createScenarioBtn').onclick=()=>{const intensity=$('#trafficIntensity').value,arrivalMean={light:180,normal:105,heavy:68,congested:42}[intensity],weatherMode=$('#weatherPattern').value;start($('#seedInput').value||'PORT-OPS-01',{policy:$('#policySelect').value==='wcost'?'hybrid':$('#policySelect').value,arrivalMean,weatherMode});closeModal()};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#pauseBtn').click()}})}
bind();start();requestAnimationFrame(loop);
})();
