(()=>{
'use strict';
const root=typeof window!=='undefined'?window:globalThis;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,n=1)=>Number(v.toFixed(n));
const key=(a,b)=>`${a}:${b}`;
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function seeded(seed){let s=hash(seed)||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const pick=(r,a)=>a[Math.floor(r()*a.length)];
const SHIP_PREFIX=['Ocean','Nordic','Pacific','Atlantic','Eastern','Liberty','Global','Blue','Golden','Silver','Mercury','Atlas','Neptune','Aurora','Orion','Seaway','Mariner','Horizon','Ever','Royal'];
const SHIP_SUFFIX=['Spirit','Trader','Voyager','Crown','Falcon','Bridge','Pioneer','Star','Haven','Dawn','Venture','Seeker','Glory','Wave','Fortune','Arrow','Quest','Pearl','Nova','Meridian'];
const TYPES={
  container:{label:'Container',loa:[170,365],beam:[27,51],draft:[8.5,14.8],cargo:[1200,7200],priority:2,baseRate:[65,105]},
  bulk:{label:'Bulk Carrier',loa:[180,300],beam:[28,48],draft:[9.5,16.2],cargo:[18000,76000],priority:1,baseRate:[900,1700]},
  tanker:{label:'Tanker',loa:[180,285],beam:[30,48],draft:[9,15.5],cargo:[18000,68000],priority:3,baseRate:[850,1450]},
  roRo:{label:'Ro-Ro',loa:[150,235],beam:[25,36],draft:[6.5,9.8],cargo:[900,2800],priority:4,baseRate:[80,130]}
};
function rngState(w){w._rng=(Math.imul(w._rng||1,1664525)+1013904223)>>>0;return w._rng/4294967296}
function wrand(w){return rngState(w)}
function wpick(w,a){return a[Math.floor(wrand(w)*a.length)]}
function fmtMin(m){const d=Math.floor(m/1440),h=Math.floor((m%1440)/60),mm=Math.floor(m%60);return `${d?'D'+d+' ':''}${String(h).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}
function event(w,type,message,shipId=null,importance=1){const e={id:++w.eventSeq,t:w.time,stamp:fmtMin(w.time),type,message,shipId,importance};w.events.unshift(e);if(w.events.length>650)w.events.length=650;return e}
function radio(w,speaker,text,shipId=null){w.radio.unshift({id:++w.radioSeq,t:w.time,stamp:fmtMin(w.time),speaker,text,shipId});if(w.radio.length>120)w.radio.length=120}
function generateShip(r,id,eta){const t=pick(r,Object.keys(TYPES)),d=TYPES[t],lerp=(a,b)=>a+r()*(b-a),loa=lerp(...d.loa),beam=lerp(...d.beam),draft=lerp(...d.draft),cargo=lerp(...d.cargo),baseRate=lerp(...d.baseRate);return{id,name:`${pick(r,SHIP_PREFIX)} ${pick(r,SHIP_SUFFIX)}`,type:t,typeLabel:d.label,loa:round(loa),beam:round(beam),draft:round(draft),cargo:Math.round(cargo),cargoRemaining:Math.round(cargo),baseRate:round(baseRate),priority:d.priority,eta,status:'scheduled',phase:'scheduled',phaseStart:0,phaseEnd:null,arrived:null,pilotStart:null,berthStart:null,cargoStart:null,cargoEnd:null,departed:null,berthId:null,pilotId:null,tugIds:[],mooringGang:null,cranes:0,waitMinutes:0,serviceMinutes:0,delayMinutes:0,weatherDelay:0,heading:90,sog:0,progress:0,deadline:eta+480+Math.floor(r()*900),notes:[],timeline:[]}}
function generate(seed='PORT-01',opts={}){const r=seeded(seed),berthCount=+opts.berths||3,pilotCount=+opts.pilots||2,tugCount=+opts.tugs||3,gangCount=+opts.gangs||2,cranes=+opts.cranes||8,arrivalRate=+opts.arrivalRate||.085,w={version:1,seed:String(seed),time:0,eventSeq:0,radioSeq:0,_rng:Math.floor(r()*1e9),settings:{discipline:opts.discipline||'fcfs',arrivalRate,weatherMode:opts.weatherMode||'variable'},weather:{wind:8,visibility:10,sea:'slight',factor:1,closure:false,label:'Good'},berths:[],pilots:[],tugs:[],gangs:[],cranes:[],ships:[],events:[],radio:[],history:[],completed:[],queueSamples:[],resourceBusy:{pilot:0,tug:0,gang:0,crane:0},resourceTotal:{pilot:0,tug:0,gang:0,crane:0}};
for(let i=0;i<berthCount;i++)w.berths.push({id:i,name:`Berth ${i+1}`,maxLoa:[230,290,370,260][i%4],maxDraft:[10.5,13.2,16.5,12][i%4],craneCap:[2,3,4,2][i%4],occupiedBy:null,busyMinutes:0,totalMinutes:0});
for(let i=0;i<pilotCount;i++)w.pilots.push({id:i,name:`Pilot ${i+1}`,busy:false,shipId:null,busyUntil:0,busyMinutes:0});
for(let i=0;i<tugCount;i++)w.tugs.push({id:i,name:`Tug ${String.fromCharCode(65+i)}`,bollardPull:45+Math.round(r()*25),busy:false,shipId:null,busyUntil:0,busyMinutes:0});
for(let i=0;i<gangCount;i++)w.gangs.push({id:i,name:`Mooring Gang ${i+1}`,busy:false,shipId:null,busyUntil:0,busyMinutes:0});
for(let i=0;i<cranes;i++)w.cranes.push({id:i,name:`QC-${i+1}`,busy:false,shipId:null,berthId:null,busyMinutes:0});
let eta=20;for(let i=0;i<18;i++){eta+=Math.max(25,Math.round((-Math.log(1-r()))/(arrivalRate/60)));w.ships.push(generateShip(r,i,eta))}
event(w,'system',`Simulation initialized with ${berthCount} berths, ${pilotCount} pilots and ${tugCount} tugs.`,null,2);return w}
function compatible(s,b){return s.loa<=b.maxLoa&&s.draft<=b.maxDraft}
function serviceEstimate(s,b,w){const craneFit=Math.max(1,Math.min(b.craneCap,Math.ceil(s.cargo/(s.type==='container'?1800:22000))));const rate=s.baseRate*craneFit*weatherFactor(w,s);return Math.max(60,s.cargo/Math.max(1,rate)*60)}
function weatherFactor(w,s){let f=w.weather.factor;if(s.type==='container'&&w.weather.wind>22)f*=.68;if(s.type==='roRo'&&w.weather.wind>28)f*=.78;return clamp(f,.3,1.15)}
function urgencyScore(s,w){const wait=Math.max(0,w.time-(s.arrived??s.eta)),proc=Math.max(1,s.cargo/s.baseRate*60);switch(w.settings.discipline){case'spt':return -proc;case'edd':return -(s.deadline-w.time);case'priority':return s.priority*500+wait;case'weighted':return s.priority*280+wait*1.4-proc*.12;default:return -s.arrived}}
function waitingShips(w){return w.ships.filter(s=>s.status==='waiting'||s.status==='anchorage').sort((a,b)=>urgencyScore(b,w)-urgencyScore(a,w))}
function bestBerth(w,s){const free=w.berths.filter(b=>b.occupiedBy==null&&compatible(s,b));if(!free.length)return null;free.sort((a,b)=>{const sa=serviceEstimate(s,a,w)+(a.maxLoa-s.loa)*.15+(a.maxDraft-s.draft)*3,sb=serviceEstimate(s,b,w)+(b.maxLoa-s.loa)*.15+(b.maxDraft-s.draft)*3;return sa-sb});return free[0]}
function freePilot(w){return w.pilots.find(p=>!p.busy)} function freeGang(w){return w.gangs.find(g=>!g.busy)} function freeTugs(w,n){const a=w.tugs.filter(t=>!t.busy);return a.length>=n?a.slice(0,n):null}
function requiredTugs(s,w){let n=s.loa>280||s.type==='tanker'?2:1;if(w.weather.wind>24)n=Math.min(3,n+1);return n}
function reserve(arr,shipId,duration,w){for(const r of arr){r.busy=true;r.shipId=shipId;r.busyUntil=w.time+duration}return arr.map(x=>x.id)}
function releaseResources(w,s){for(const p of w.pilots)if(p.shipId===s.id&&p.busyUntil<=w.time){p.busy=false;p.shipId=null}for(const t of w.tugs)if(t.shipId===s.id&&t.busyUntil<=w.time){t.busy=false;t.shipId=null}for(const g of w.gangs)if(g.shipId===s.id&&g.busyUntil<=w.time){g.busy=false;g.shipId=null}}
function setPhase(w,s,phase,duration=0){s.phase=phase;s.status=phase;s.phaseStart=w.time;s.phaseEnd=duration?w.time+duration:null;s.progress=0;s.timeline.push({t:w.time,phase});}
function scheduleInbound(w){if(w.weather.closure)return;for(const s of waitingShips(w)){const b=bestBerth(w,s);if(!b)continue;const p=freePilot(w),g=freeGang(w),tugs=freeTugs(w,requiredTugs(s,w));if(!p||!g||!tugs)continue;b.occupiedBy=s.id;s.berthId=b.id;s.pilotId=p.id;s.mooringGang=g.id;reserve([p],s.id,85,w);s.tugIds=reserve(tugs,s.id,110,w);reserve([g],s.id,130,w);s.pilotStart=w.time;setPhase(w,s,'pilot_dispatch',18);event(w,'operation',`${s.name} called forward from anchorage for ${b.name}.`,s.id,2);radio(w,'Port Control',`${s.name}, proceed to Pilot Station Alpha. Pilot boat is underway.`,s.id);break}}
function beginCargo(w,s){const b=w.berths[s.berthId],need=Math.max(1,Math.min(b.craneCap,Math.ceil(s.cargo/(s.type==='container'?1800:22000)))),free=w.cranes.filter(c=>!c.busy).slice(0,need);if(!free.length){setPhase(w,s,'alongside_wait_crane',15);event(w,'delay',`${s.name} alongside but waiting for cargo equipment.`,s.id);return}s.cranes=free.length;for(const c of free){c.busy=true;c.shipId=s.id;c.berthId=b.id}s.cargoStart=w.time;setPhase(w,s,'cargo',0);event(w,'cargo',`Cargo operations commenced on ${s.name} with ${free.length} crane${free.length>1?'s':''}.`,s.id,2);radio(w,'Terminal',`${s.name}, all fast. Cargo team commencing operations.`,s.id)}
function finishCargo(w,s){s.cargoEnd=w.time;for(const c of w.cranes)if(c.shipId===s.id){c.busy=false;c.shipId=null;c.berthId=null}s.cranes=0;const p=freePilot(w),g=freeGang(w),tugs=freeTugs(w,requiredTugs(s,w));if(!p||!g||!tugs){setPhase(w,s,'departure_wait',15);return}s.pilotId=p.id;reserve([p],s.id,70,w);s.tugIds=reserve(tugs,s.id,75,w);s.mooringGang=g.id;reserve([g],s.id,55,w);setPhase(w,s,'unmooring',18);event(w,'operation',`${s.name} completed cargo and requested outbound clearance.`,s.id,2);radio(w,'Port Control',`${s.name}, outbound pilot confirmed. Tugs make fast fore and aft.`,s.id)}
function transition(w,s){switch(s.phase){case'pilot_dispatch':setPhase(w,s,'pilot_boarding',12);radio(w,'Pilot Boat',`${s.name}, reduce to six knots and make a lee for pilot boarding.`,s.id);break;case'pilot_boarding':setPhase(w,s,'inbound_channel',22);radio(w,'Pilot',`Bridge, pilot on board. Dead slow ahead. Keep mid-channel, course zero-eight-five.`,s.id);break;case'inbound_channel':setPhase(w,s,'tug_make_fast',14);radio(w,'Pilot',`Tugs, make fast centre lead forward and aft. Stand by for braking.`,s.id);break;case'tug_make_fast':setPhase(w,s,'turning_basin',20);break;case'turning_basin':setPhase(w,s,'final_approach',18);radio(w,'Pilot',`Port ten. Tug Alpha pull easy. Stern tug check the swing.`,s.id);break;case'final_approach':setPhase(w,s,'parallel_berthing',14);radio(w,'Pilot',`Dead slow astern. Both tugs push easy. Bring her parallel, fifty metres off.`,s.id);break;case'parallel_berthing':setPhase(w,s,'mooring',20);radio(w,'Mooring Station',`Heaving lines received. Headlines and stern lines going ashore.`,s.id);break;case'mooring':s.berthStart=w.time;beginCargo(w,s);break;case'alongside_wait_crane':beginCargo(w,s);break;case'departure_wait':finishCargo(w,s);break;case'unmooring':setPhase(w,s,'outbound',24);radio(w,'Pilot',`All lines clear. Tug aft pull easy. Dead slow ahead to the fairway.`,s.id);break;case'outbound':completeShip(w,s);break}}
function completeShip(w,s){const b=w.berths[s.berthId];if(b)b.occupiedBy=null;s.departed=w.time;s.status=s.phase='departed';s.serviceMinutes=s.departed-(s.arrived??s.eta);w.completed.push(s.id);releaseResources(w,s);event(w,'departure',`${s.name} cleared the breakwater and departed.`,s.id,2);radio(w,'Port Control',`${s.name}, clear of port limits. Safe voyage.`,s.id)}
function updateWeather(w){if(w.settings.weatherMode==='calm'){Object.assign(w.weather,{wind:8,visibility:10,sea:'slight',factor:1,closure:false,label:'Good'});return}if(w.time%60!==0)return;const x=wrand(w);if(x<.08){Object.assign(w.weather,{wind:31+Math.round(wrand(w)*10),visibility:2+wrand(w)*3,sea:'rough',factor:.48,closure:wrand(w)<.25,label:'Severe'});event(w,'weather',w.weather.closure?'Channel temporarily closed by severe weather.':'Severe weather reducing port productivity.',null,3)}else if(x<.28)Object.assign(w.weather,{wind:20+Math.round(wrand(w)*8),visibility:5+wrand(w)*4,sea:'moderate',factor:.72,closure:false,label:'Restricted'});else Object.assign(w.weather,{wind:6+Math.round(wrand(w)*12),visibility:8+wrand(w)*5,sea:'slight',factor:.95+wrand(w)*.1,closure:false,label:'Good'})}
function spawnArrivals(w){for(const s of w.ships)if(s.status==='scheduled'&&s.eta<=w.time){s.arrived=w.time;s.status=s.phase='waiting';event(w,'arrival',`${s.name} arrived at pilot boarding ground and joined the queue.`,s.id,2);radio(w,s.name,`Port Control, ${s.name}, arrived pilot station, ready in all respects.`,s.id)}}
function cargoTick(w,s,dt){const rate=s.baseRate*Math.max(1,s.cranes)*weatherFactor(w,s);const qty=rate*dt/60;s.cargoRemaining=Math.max(0,s.cargoRemaining-qty);if(w.weather.factor<.8)s.weatherDelay+=dt*(1-w.weather.factor);if(s.cargoRemaining<=0)finishCargo(w,s)}
function tickResources(w,dt){for(const b of w.berths){b.totalMinutes+=dt;if(b.occupiedBy!=null)b.busyMinutes+=dt}for(const p of w.pilots)if(p.busy)p.busyMinutes+=dt;for(const t of w.tugs)if(t.busy)t.busyMinutes+=dt;for(const g of w.gangs)if(g.busy)g.busyMinutes+=dt;for(const c of w.cranes)if(c.busy)c.busyMinutes+=dt}
function step(w,dt=1){for(let m=0;m<dt;m++){w.time++;updateWeather(w);spawnArrivals(w);tickResources(w,1);for(const s of w.ships){if(s.status==='waiting')s.waitMinutes++;if(s.phase==='cargo')cargoTick(w,s,1);else if(s.phaseEnd&&w.time>=s.phaseEnd)transition(w,s);releaseResources(w,s)}scheduleInbound(w);if(w.time%15===0)w.queueSamples.push({t:w.time,q:waitingShips(w).length});if(w.time%60===0)w.history.push(metrics(w));}return w}
function metrics(w){const done=w.completed.map(id=>w.ships[id]),active=w.ships.filter(s=>s.arrived!=null&&s.departed==null),waits=[...done,...active].map(s=>s.waitMinutes),berthUtil=w.berths.reduce((z,b)=>z+(b.totalMinutes?b.busyMinutes/b.totalMinutes:0),0)/Math.max(1,w.berths.length),pilotUtil=w.pilots.reduce((z,p)=>z+p.busyMinutes,0)/Math.max(1,w.time*w.pilots.length),tugUtil=w.tugs.reduce((z,t)=>z+t.busyMinutes,0)/Math.max(1,w.time*w.tugs.length),craneUtil=w.cranes.reduce((z,c)=>z+c.busyMinutes,0)/Math.max(1,w.time*w.cranes.length);return{t:w.time,queue:waitingShips(w).length,completed:done.length,avgWait:waits.length?waits.reduce((a,b)=>a+b,0)/waits.length:0,maxWait:waits.length?Math.max(...waits):0,berthUtil,pilotUtil,tugUtil,craneUtil,throughputPerDay:w.time?done.length/(w.time/1440):0,avgPortStay:done.length?done.reduce((z,s)=>z+(s.departed-s.arrived),0)/done.length:0}}
function queueTable(w){return waitingShips(w).map((s,i)=>({rank:i+1,id:s.id,name:s.name,type:s.typeLabel,loa:s.loa,draft:s.draft,wait:s.waitMinutes,priority:s.priority,deadline:s.deadline,compatible:w.berths.filter(b=>compatible(s,b)).map(b=>b.name)}))}
function berthPlan(w){return w.berths.map(b=>{const s=b.occupiedBy==null?null:w.ships[b.occupiedBy];return{id:b.id,name:b.name,maxLoa:b.maxLoa,maxDraft:b.maxDraft,occupiedBy:s?.name||null,shipId:s?.id??null,util:b.totalMinutes?b.busyMinutes/b.totalMinutes:0}})}
function orSnapshot(w){const m=metrics(w),q=queueTable(w);return{discipline:w.settings.discipline,objective:{avgWaitingTime:round(m.avgWait),throughput:round(m.throughputPerDay,2),berthUtilization:round(m.berthUtil*100),maxQueueWait:round(m.maxWait)},queue:q,berths:berthPlan(w),notes:[`Queue discipline: ${w.settings.discipline.toUpperCase()}`,`Compatible-berth feasibility enforces LOA and draft constraints.`,`Berth selection minimizes estimated processing time plus berth-fit penalty.`,`Service time adapts to crane allocation and weather productivity.`]}}
function setDiscipline(w,d){if(['fcfs','spt','edd','priority','weighted'].includes(d)){w.settings.discipline=d;event(w,'system',`Queue discipline changed to ${d.toUpperCase()}.`,null,1)}}
function serialize(w){return JSON.stringify(w)} function deserialize(s){return JSON.parse(s)}
root.PortSim={generate,step,metrics,queueTable,berthPlan,orSnapshot,setDiscipline,compatible,serviceEstimate,weatherFactor,waitingShips,fmtMin,serialize,deserialize,TYPES};
})();